variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR  

cache:
    key:
      files:      
        - package.json
    paths:
      - node_modules/

stages:
    - build 
    - test
    - archive
    - deploy
    
build:
  stage: build
  environment:
        name: development
        url: http://188.166.214.118:8081/
  tags:
      - s1
  artifacts:
    public: true    
    when: on_success
    paths:
      - node_modules/

  before_script: 
    - ansible-playbook -i hosts playbook/playbook.yml --syntax-check
    - ansible-playbook -i hosts playbook/playbook.yml

  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success          
      allow_failure: true
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^src/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^src/'
      when: manual
      allow_failure: true
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'  # Checking for the presence of a variable is possible      
    - if: '$CI_COMMIT_TAG != ""'
  
  script:
    - npm install  

  retry:
      max: 2
      when: always   
  allow_failure: true

  after_script:
        - echo "Build development complete"    

test:
    stage: test
    environment:
        name: development
        url: http://188.166.214.118:8081/
    tags:
        - s1
    script:
      - echo "skipping...." #npm run test
      - echo "NPM Test Success..."

    only:
      - master 

    retry:
      max: 2
      when:         
        - runner_system_failure
        - stuck_or_timeout_failure
    allow_failure: true
    when: delayed
    start_in: 1 minutes 

    after_script:
        - echo "Test development complete..."   

archive:
    stage: archive
    environment:
        name: development
        url: http://188.166.214.118:8081/
    tags:
        - s1
    before_script: 
      - ls -ltr $DIR_RELEASE
    script:
        - | 
          if [ -d $DIR_RELEASE/web_api ]; then 
            echo "Directory Is exists.";
          else 
            mkdir -p $DIR_RELEASE/web_api; 
            echo "Create Directory Success...";
          fi
        - | 
          if [ -f "*.zip" ]; then 
            echo "This package already downloaded..."; 
            unzip *.zip -d $DIR_RELEASE/web_api/; 
          else 
            echo "preparing Archive package......";
            cd $CI_BUILDS_DIR && zip -r node_modules.zip node_modules && cp -r node_modules.zip $DIR_RELEASE/web_api/             
            echo "Archiving Package Success.." 
          fi
    only:
      - master   

    retry:
      max: 2
      when: always
    allow_failure: true
    when: delayed
    start_in: 5 minutes
    after_script:
        - echo "Archive development complete..."

deploy:
    stage: deploy
    environment:
        name: development
        url: http://188.166.214.118:8081/
    tags:
        - s1
    before_script:
        - echo "backup dir web api"        
        - cd /home/appuser01/sicepat_api 
        - | 
          if [ -e "node_modules_`date +%y_%m_%d`.tar.gz" ]; then 
            echo "Yes, file exists"; 
          else 
            echo "Compres Proses..."; 
            tar -cf node_modules_`date +%y_%m_%d`.tar.gz node_modules; 
            echo "compress success..."; 
          fi
               
    script: 
        - cd $DIR_RELEASE/web_api
        - echo "Extract Package...."
        - unzip node_modules.zip && ls -ltr node_modules
        - echo "deploy Success.."
        #- su appuser01
        #- echo "Checking Status Service.."
        #- cd /home/appuser01/sicepat_api && pm2 status
        #- echo "Stop Service Backend..."
        #- cd /home/appuser01/sicepat_api && pm2 stop && pm2 status
        #- echo "Preparing remove packages..."
        #- rm -rf /home/appuser01/sicepat_api/node_modules && ls -ltr /home/appuser01/sicepat_api/node_modules
        #- echo "Remove Packages Success..."
        #- echo "Copy Packages..."
        #- mv $DIR_RELEASE/web_api/node_modules /home/appuser01/sicepat_api/ && ls -ltr /home/appuser01/sicepat_api/node_modules
        #- sudo chown -Rv appuser01:appuser01 /home/appuser01/sicepat_api/node_modules && sudo chmod -Rv 775 /home/appuser01/sicepat_api/node_modules
        #- sudo pm2 start && sudo pm2 status


    only:
      - master

    retry:
      max: 2
      when: always
    allow_failure: true
    when: delayed
    start_in: 1 minutes
    after_script:
        - echo "Deploy development complete..."
